### ISSUE TITLE
Alguns problemas no montador

### ISSUE THREAD

**Issue by uandersonricardo** [leamorim/Infra-de-Hardware-EC-CIn-UFPE#1]
1. O montador está gerando o arquivo "instructions.mif", mas a memória lê "instruction.mif" (sem o s).
2. Os montador está gerando os opcodes de bne, bge e blt errados (era pra ser 1100111 e está gerando 1100011)
3. Números negativos não estão funcionando no montador (ex: addi x1, x0, -5)

**Comment by leamorim** [comment]
@uandersonricardo a memória agora lê do arquivo "instructions.mif", baixa de novo a pasta dos módulos (1).
O opcode do bne, bge e blt já foram consertados (2), pode baixar novamente o montador.
Agora ainda não implementamos números negativos no montador (3).
Em breve @JulianaDamurie vai ver isso

**Comment by uandersonricardo** [comment]
beleza, valeu!
